==== 1.2.1 *Current Situation*

Being consistent in a fitness routine is a very common challenge that even athletes struggle with. While many people begin their fitness journey due to important health reasons, sports or mantaining a fit and healthy lifestyle, sustaining all of these habits proves difficult for most people. A contributing factor for inconsistency is having to track their fitness journey like calorie & nurition intake, exercise schedule, workout logging, etc, through different apps, notebooks or even mental notes. 
Having all of these scattered apps prevents the ability to easily visualize their progress and this can weaken motivation. These apps also can overwhelm users with extensive features, when most users just want to do something simple like calorie counting or log their workouts, and some only offer one of the desired components. As a result, users must be switching from app to app so that they can track all their progress. Additionally, most apps don't even provide necessary feedback that helps reassure the users and keeps them motivated to stay consistent with a program. Having a less centralized and less engaging method to track fitness makes users create a cycle while browsing through fitness apps that can exhaust the users, which can lead to them stop tracking their progress and discontinue healthy habits.
