name: Standard Issue
description: Use this template for all project issues
title: "[Category] Short, action-oriented title"
labels: []
assignees: []

body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: Clearly state the goal of this issue in one or two concise sentences.
      placeholder: What is this issue trying to accomplish?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide context and details about what needs to be done and what the task should produce.
      placeholder: Add background, constraints, links, and expected output.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Add as many as needed. Use checkboxes so they can be checked off in the issue.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: dropdown
    id: expected_timeframe
    attributes:
      label: Expected Time Frame
      description: When should this issue ideally be completed?
      options:
        - This week
        - Next week
        - This sprint
        - This milestone
        - Next milestone
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How time-sensitive is this issue?
      options:
        - "1 - Low"
        - "2"
        - "3"
        - "4"
        - "5 - High"
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty
      description: How complex is this issue to implement?
      options:
        - "1 - Trivial"
        - "2"
        - "3"
        - "4"
        - "5 - Complex"
    validations:
      required: true

  - type: textarea
    id: recommended_assignee
    attributes:
      label: Recommended Assigned Developer
      description: Use @username. Mentions resolve normally after the issue is created.
      placeholder: |
        @username
        Reason (optional):
    validations:
      required: false